name: Weave CI/CD

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    lint:
        name: Lint and Type Check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'
                  registry-url: https://npm.pkg.github.com/
                  scope: '@jorgenswiderski'
            - name: Install dependencies
              run: npm ci
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GHP_TOKEN }}
            - name: Run lint
              run: npm run lint
            - name: Run type check
              run: npm run type-check

    test:
        name: Test
        needs: lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'
                  registry-url: https://npm.pkg.github.com/
                  scope: '@jorgenswiderski'
            - name: Install dependencies
              run: npm ci
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GHP_TOKEN }}
            - name: Run tests
              run: npm run test

    deploy:
        name: Deploy to EC2
        needs: test
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USERNAME }}
                  key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
                  script: |
                      set -e
                      cd weave
                      git config --global credential.helper store
                      echo "url=https://github.com" >> ~/.git-credentials
                      echo "   username=x-access-token" >> ~/.git-credentials
                      echo "   password=${{ secrets.GHP_TOKEN }}" >> ~/.git-credentials          
                      git pull origin master
                      docker-compose up --build -d
