name: Weave CI/CD

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    lint:
        name: Lint and Type Check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'
                  registry-url: https://npm.pkg.github.com/
                  scope: '@jorgenswiderski'
            - name: Install dependencies
              run: npm ci
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GHP_TOKEN }}
            - name: Run lint
              run: npm run lint
            - name: Run type check
              run: npm run type-check

    test:
        name: Test
        needs: lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'
                  registry-url: https://npm.pkg.github.com/
                  scope: '@jorgenswiderski'
            - name: Install dependencies
              run: npm ci
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GHP_TOKEN }}
            - name: Run tests
              run: npm run test

    deploy:
        name: Deploy to EC2
        needs: test
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - name: SSH and Deploy
              id: deploy
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USERNAME }}
                  key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
                  script: |
                      set -e
                      cd weave
                      git config --global credential.helper store
                      git credential approve <<EOF
                      protocol=https
                      host=github.com
                      username=x-access-token
                      password=${{ secrets.GHP_TOKEN }}
                      EOF
                      set +e
                      rm -r node_modules
                      set -e
                      git pull origin master
                      docker-compose pull
                      docker-compose up --build -d

            - name: Rollback
              if: failure() && steps.deploy.outcome == 'failure'
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USERNAME }}
                  key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
                  script: |
                      set -e
                      cd weave
                      git reset --hard HEAD~1
                      docker-compose pull
                      docker-compose up --build -d

            - name: Cleanup Docker Environment
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USERNAME }}
                  key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
                  script: |
                      set -e
                      docker image prune -f
                      docker container prune -f
                      docker network prune -f
                      docker builder prune -f --filter "until=72h"
